### ISSUE TITLE
Typo in TTL example

### ISSUE THREAD

**Issue by VAveryanov8** [Altinity/kbissues#1]
Page - [ConfigureTTL](https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-system-tables-eat-my-disk#Systemtableseatmydisk-YoucanconfigureTTL:)
Example with typo: 
```bash
$ cat /etc/clickhouse-server/config.d/query_log_ttl.xml
<?xml version="1.0"?>
<yandex>
    <query_log>
        <database>system</database>
        <table>query_log</table>
        <engine>ENGINE = MergeTree PARTITION BY (event_date) 
                ORDER BY (event_time) 
                TTL  event_date + 14 day DELETE
                SETTINGS ttl_only_drop_parts=1
        </engine>
        <flush_interval_milliseconds>7500</flush_interval_milliseconds>
    </query_log>
</yandex>
``` 
Where is typo: Looks like TTL config should have INTERVAL keyword before 14 days, e.g.
                TTL  event_date + **INTERVAL** 14 day DELETE   

Thanks in advance :)

**Comment by johnhummelAltinity** [comment]
Thanks - I'll run this by the team and get that fixed up. Thanks for the info!

**Comment by johnhummelAltinity** [comment]
@VAveryanov8 Looks like someone fixed it before I got to it.  Sorry it took so long to get back to you.
